services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  Doctrine\ORM\EntityManagerInterface:
    class: webignition\BasilWorker\PersistenceBundle\Tests\Mock\NullEntityManager
